name: Restrict Branch Delete

on:
  push:
    branches:
      - main

jobs:
  check_branch_delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Branch Delete
        run: |
          if [ "${{ github.event_name }}" = "delete" ]; then
            echo "Error: Deleting branches is not allowed."
            exit 1
          fi